<?php
// Rugby positions for dropdown
return [
    'Loosehead Prop (1)',
    'Hooker (2)',
    'Tighthead Prop (3)',
    'Lock (4)',
    'Lock (5)',
    'Blindside Flanker (6)',
    'Openside Flanker (7)',
    'Number Eight (8)',
    'Scrum-half (9)',
    'Fly-half (10)',
    'Left Wing (11)',
    'Inside Centre (12)',
    'Outside Centre (13)',
    'Right Wing (14)',
    'Full-back (15)',
    'Reserve 1',
    'Reserve 2',
    'Reserve 3',
    'Reserve 4',
    'Reserve 5',
    'Reserve 6',
    'Reserve 7',
    'Reserve 8',
    'Reserve 9',
    'Reserve 10',
];
